# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'final-project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'SCLAlertView'
  pod 'lottie-ios'
  pod 'ProgressHUD'
  pod 'TextFieldEffects'
  pod 'PMSuperButton'

end
