# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'day-7' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for day-7
  
  pod 'SCLAlertView', '~> 0.8'

end
